#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
xsetroot -cursor_name left_ptr &
xrdb $HOME/.Xresources &
feh --bg-fill $HOME/Pictures/wallpapers/palms.jpg &
picom &
$HOME/.config/polybar/launch.sh &

bspc monitor -d TERM WEB DISC MP3 DOC MISC

bspc config border_width        0
bspc config window_gap          8
bspc config focus_follows_pointer true

bspc config split_ratio          0.51
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^6' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a Discord desktop='^3'
bspc rule -a Zathura desktop='^5' state=tiled follow=on
bspc rule -a cmus desktop='^4'
